### ISSUE TITLE
Complete Drizzle ORM support

### ISSUE THREAD

**Issue by avanderbergh** [pgvector/pgvector-node#10]
I'm really keen on getting **pgvector** supported in `drizzle-orm` and `drizzle-kit`.

There's an open issue on drizzle-kit to hopefully make the current experimental implementation work
https://github.com/drizzle-team/drizzle-kit-mirror/issues/115

I see this is planned for the `0.1.5` release.

Is it possible to perhaps publish the upcoming releases under a `@next` tag so we could use it with workarounds?

**Comment by ankane** [comment]
Hi @avanderbergh, thanks for raising the issue with Drizzle Kit. You can point your `package.json` to GitHub to use unreleased changes.

**Comment by jschuur** [comment]
> Hi @avanderbergh, thanks for raising the issue with Drizzle Kit. You can point your `package.json` to GitHub to use unreleased changes.

I'm listing the current version from GitHub as an npm dependency, but get a TypeScript error importing from `pgvector/drizzle-orm`

```ts
// Cannot find module 'pgvector/drizzle-orm' or its corresponding type declarations.ts(2307)
import { l2Distance } from 'pgvector/drizzle-orm';
```

I was able to get around it with `declare module 'pgvector/drizzle-orm';` in a `.d.ts` file in the mean time at least.

**Comment by ankane** [comment]
Hmm, the types are in `types/drizzle-orm/index.d.ts`, which is referenced in [package.json](https://github.com/pgvector/pgvector-node/blob/009773442e9a797b13ea58a336dfd54237cb264e/package.json#L16).

**Comment by jschuur** [comment]
> Hmm, the types are in `types/drizzle-orm/index.d.ts`, which is referenced in [package.json](https://github.com/pgvector/pgvector-node/blob/009773442e9a797b13ea58a336dfd54237cb264e/package.json#L16).

If you'd like to replicate it locally, rename `global.d.ts` in [this repo](https://github.com/jschuur/embeddings-search-test) and visit `src/db/db/ts`.

**Comment by hyusetiawan** [comment]
yeah it'd be great to get the drizzle support to a "productive" state at least so we can continue evaluating until future releases :)

**Comment by ankane** [comment]
Just pushed 0.1.5 with experimental support.

@jschuur The release also adds support for `"moduleResolution": "node"`, which should fix the import error.
