### ISSUE TITLE
Cannot import library

### ISSUE THREAD

**Issue by Klingefjord** [pgvector/pgvector-node#11]
For some reason I cannot import the library even though it is in my node_modules folder (ran `npm install pgvector`)
![Screenshot 2023-08-10 at 13 42 09](https://github.com/pgvector/pgvector-node/assets/22666776/fe53bc36-e126-460b-b22e-37d9d9f14c67)
![Screenshot 2023-08-10 at 13 41 56](https://github.com/pgvector/pgvector-node/assets/22666776/2d789555-5235-4fb3-b0ad-d6b8127cf1b3)

Using TypeScript.

**Comment by amine-mf** [comment]
Check the following for a fix : https://github.com/pgvector/pgvector-node/issues/2#issuecomment-1491149793
Please note also my comment down the bottom as you might be in the same situation where changing the moduleResolution is a big piece of work for big projects : https://github.com/pgvector/pgvector-node/issues/2#issuecomment-1682261534

**Comment by ankane** [comment]
Hi @Klingefjord and @amine-mf, added support for `"moduleResolution": "node"` in the commit above.

**Comment by seyfer** [comment]
> Using TypeScript.

I have to use it with `@ts-ignore` at the top of the import, it works.
