### ISSUE TITLE
TypeError: exports.knex.schema.enableExtension is not a function

### ISSUE THREAD

**Issue by seyfer** [pgvector/pgvector-node#16]
Hey,

there is a mistake in docs for usage with Knex.js 
and if I go to the `schema: Knex.SchemaBuilder;` type, there is no such method.

**Comment by ankane** [comment]
Hi @seyfer, importing the library adds that method (first step in the docs).

```javascript
import pgvector from 'pgvector/knex';
```

**Comment by seyfer** [comment]
@ankane ah ok, this is because I use Typescript. then I will have to do `@ts-ignore`
