### ISSUE TITLE
Distance column param issue with sequelize

### ISSUE THREAD

**Issue by fTrestour** [pgvector/pgvector-node#17]
Hi!

I'm new to this library and I'm trying to run this query with sequelize:
```js
const lessons = await Table.findAll({
      include: [
        {
          association: 'association',
        },
      ],
      order: cosineDistance('Table.embedding_column', searchEmbedding, sequelize),
      subQuery: false,
      limit: 15,
    })
```

Sequelize makes it necessary to specify `Table.` in this situation and the distance function from the package generates  `"Table.embedding_column" <=> ...` while it should be `"Table"."embedding_column" <=> ...` to have it work properly.

I am missing something or is this a bug?

If it's a bug, I guess a split on `.` for the column arg and mapping `sequelize.dialect.queryGenerator.quoteIdentifier` to each element [here](https://github.com/pgvector/pgvector-node/blob/b2ab8fc4c1577b2db19c8a72f3f2f3e9ad12e767/src/sequelize/index.js#L46) could be a fix?

**Comment by ankane** [comment]
Hi @fTrestour, quoting the column is by design. Added support for passing `sequelize.literal('"Table".embedding_column')` in the commit above.
