### ISSUE TITLE
Will it support typescript?

### ISSUE THREAD

**Issue by devilyouwei** [pgvector/pgvector-node#2]
I am using node.js with TypeScript. I got an issue that DataTypes.VECTOR does not exist even if using registerType(Sequelize). Also, I will use an ORM which can cause more issues when DataType is not supported.

**Comment by ankane** [comment]
Hi @devilyouwei, added code for generating declaration files in the [typescript](https://github.com/pgvector/pgvector-node/compare/typescript) branch, but they don't appear to be needed for new TypeScript projects (`npx tsc --init`). What error are you seeing with TypeScript?

Also, I'm not sure how to reproduce the `DataTypes.VECTOR` issue. Can you paste the full error message, backtrace, and relevant code?

**Comment by ankane** [comment]
fwiw, `@Column(DataType.VECTOR(1536))` seems to work if you call `pgvector.registerType(Sequelize)`, but glad you found another approach that works.

**Comment by ankane** [comment]
Just pushed 0.1.1, which includes types.

Note: `moduleResolution` must be set to `node16`/`nodenext` in `tsconfig.json` for TypeScript to find them.

**Comment by wlaurance** [comment]
I'm trying this now and I don't believe the types are included in the actual package file.

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1059214/229676790-564c789e-5e1a-457d-adbc-d4d17cc64d05.png">


I tried to fix it with local linking the package and I made this change to make it work better https://github.com/pgvector/pgvector-node/pull/3

**Comment by amine-mf** [comment]
> Just pushed 0.1.1, which includes types.
> 
> Note: `moduleResolution` must be set to `node16`/`nodenext` in `tsconfig.json` for TypeScript to find them.

It seems like more than one person struggle with the issue, and it is not always an (easy) option to just migrate to `nodenext`. 
Out of 8 issues, 2 are related to this (#11)
Is there any other workarounds (Could not find any myself)? Is there any chance to support `node` module resolution?
