### ISSUE TITLE
drizzle-orm integration cannot generate vector columns

### ISSUE THREAD

**Issue by davidgomes** [pgvector/pgvector-node#21]
If I try to generate a PG table with a column like so:

```
embedding: vector('embedding', {dimensions: 1536}),
```

Then, the drizzle-kit generated migration will look like this:

```
ALTER TABLE "documents" ADD COLUMN "embedding" "vector(1536)";
```

This is not valid SQL in Postgres, it should be:

```
ALTER TABLE "documents" ADD COLUMN "embedding" vector(1536);
```

(Otherwise, you get `ERROR:  type "vector(1536)" does not exist`)

I am not 100% sure if this is an issue with this extension or not, but figured I'd report it here.

**Comment by ankane** [comment]
Hi @davidgomes, unfortunately, this is a current limitation of Drizzle Kit ([docs](https://github.com/pgvector/pgvector-node?tab=readme-ov-file#drizzle-orm)).

https://github.com/drizzle-team/drizzle-kit-mirror/issues/115

**Comment by davidgomes** [comment]
Thank you!

**Comment by gvkhna** [comment]
This has, i believe, finally been addressed. 

https://github.com/drizzle-team/drizzle-orm/pull/2360
