### ISSUE TITLE
How to do a "where embedding is within some distance" query with Kysely and pgvector?

### ISSUE THREAD

**Issue by lancejpollard** [pgvector/pgvector-node#24]
Hello there! Super excited to try using this for dictionary definitions! Wanted to cross-post [How to do Vector Embedding query in Kysely/PostgreSQL with pgvector?](https://stackoverflow.com/questions/78759406/how-to-do-vector-embedding-query-in-kysely-postgresql-with-pgvector) here to see if you had any ideas. Thanks so much for your time.

**Comment by ankane** [comment]
Hi @lancejpollard, you can use `where(cosineDistance('embedding', [1, 2, 3]), '<', 0.1)`.
