### ISSUE TITLE
knext

### ISSUE THREAD

**Issue by nickgrato** [pgvector/pgvector-node#25]
when trying to use knex.schema.enableExtendion('vector') I get error "Property 'enableExtension' does not exist on type 'SchemaBuilder'."

looking at the knex node module looks like 'enableExtension' is not there?

/node_modules/knex/lib/schema/builder.js

// Each of the schema builder methods just add to the
// "_sequence" array for consistency.
[
  'createTable',
  'createTableIfNotExists',
  'createTableLike',
  'createView',
  'createViewOrReplace',
  'createMaterializedView',
  'refreshMaterializedView',
  'dropView',
  'dropViewIfExists',
  'dropMaterializedView',
  'dropMaterializedViewIfExists',
  'createSchema',
  'createSchemaIfNotExists',
  'dropSchema',
  'dropSchemaIfExists',
  'createExtension',
  'createExtensionIfNotExists',
  'dropExtension',
  'dropExtensionIfExists',
  'table',
  'alterTable',
  'view',
  'alterView',
  'hasTable',
  'hasColumn',
  'dropTable',
  'renameTable',
  'renameView',
  'dropTableIfExists',
  'raw',
]

**Comment by ankane** [comment]
Hi @nickgrato, check out #16.

**Comment by nickgrato** [comment]
> Hi @nickgrato, check out #16.

yea so I had that import , what I actually ended up having to do was plat around with where that import was, I ended up having the import in the knex migration file, seemed like when I just had it in my knex file it would work on my first docker build then any hot re-loads i would get that error.. not sure if there is specific nextjs docs you would want to add since that is such a hot use case at the moment, thanks for getting back to me though.
