### ISSUE TITLE
Knex Import //  table.vector is not a function

### ISSUE THREAD

**Issue by MichaelVIU** [pgvector/pgvector-node#26]
Having trouble following these instructions:
https://github.com/pgvector/pgvector-node/blob/master/tests/knex.test.mjs

I'm just creating the database schema (and not using pgvector anywhere else at the moment)
`import pgvector from 'pgvector/knex';`
Doesn't work for me (looks like the code to extend knex is not executed).

Just using `import 'pgvector/knex';` fixes it for me.

**Comment by ankane** [comment]
Hi @MichaelVIU, thanks for sharing. I'm not sure how to reproduce (the test case runs fine), so it may be something specific to your setup.
