### ISSUE TITLE
Does this work for cloud databases?

### ISSUE THREAD

**Issue by sinclairnick** [pgvector/pgvector-node#4]
I'm far from a database wiz. So I'm wondering whether this approach works to get around e.g. Google Cloud SQL's lack of support for the `pgvector` extension?

**Comment by ankane** [comment]
Hi @sinclairnick, this library requires pgvector to be installed on the database server, so it won't work with Google Cloud SQL yet. https://github.com/pgvector/pgvector#hosted-postgres
